version: "3.8"

services:
  mysql-db:
    build:
      context: .
      dockerfile: ./mysql-db/Dockerfile
    restart: always
    env_file: .env
    expose:
      - 3306
    ports:
      - "3306:3306"

  app:
    build: .
    command: ["python", "githubforker/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    expose:
      - 8000
    ports:
      - "8000:8000"
    restart: always
    env_file: .env
    depends_on:
      - mysql-db

volumes:
  mysql_data: